version: '3'
services:
  app:
    container_name: blog-app
    build: .
    restart: on-failure
    env_file:
      - .env
    environment:
      - GO_ENV=${GO_ENV}
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
    ports:
      - 8000:8080
    volumes:
      - api:/app
    depends_on:
      - postgres-db
    networks:
      - app_backend
  postgres-db:
    image: postgres:15-alpine
    container_name: db_postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - DB_HOST=${DB_HOST}
    ports:
      - ${DB_PORTS}:${DB_PORT}
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - app_backend

volumes:
  api:
  database:
networks:
  app_backend:
    driver: bridge
